language:
  - cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libstdc++-5-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libstdc++-6-dev
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls

install:

  # verify installed versions
  - which g++
  - g++ -v
  - pwd

script:
  - make clean
  - make 
  - make clean
  - make texeltest
  - ./texeltest

after_success:
  - coveralls --exclude objdef --exclude objdeftest --exclude test --exclude util --exclude bookgui --gcov-options '\-lp -o objdeftest/'  
  - pwd
  - ls
  - ls objdeftest

notifications:
  webhooks: https://coveralls.io/webhook
