language:
  - cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libstdc++-5-dev
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
  - eval "${MATRIX_EVAL}"
  - pip install --user cpp-coveralls

install:

  # verify installed versions
  - which g++
  - g++ -v

script:
  - make clean
  - make 
  - make clean
  - make texeltest
  - ./texeltest

after_success:
  - coveralls --exclude objdef --exclude objdeftest --exclude test --exclude util --exclude bookgui --gcov-options '\-lp -o objdeftest/'  
